"""Конфигурация: типизированная схема и загрузчик."""

from .loader import DEFAULT_CONFIG_PATH, load_config, load_dotenv
from .schema import (
    AECConfig,
    AppConfig,
    AttentionConfig,
    AudioConfig,
    JarvisConfig,
    LLMConfig,
    LoggingConfig,
    MemoryConfig,
    PersonaConfig,
    ProviderConfig,
    RouterConfig,
    RuntimeConfig,
    SkillsConfig,
    STTConfig,
    TaskProfile,
    TTSConfig,
    VADConfig,
    VerbatimRule,
    WakeWordConfig,
)

__all__ = [
    "AttentionConfig",
    "DEFAULT_CONFIG_PATH",
    "AppConfig",
    "AudioConfig",
    "JarvisConfig",
    "LLMConfig",
    "LoggingConfig",
    "MemoryConfig",
    "PersonaConfig",
    "ProviderConfig",
    "RouterConfig",
    "VerbatimRule",
    "RuntimeConfig",
    "STTConfig",
    "SkillsConfig",
    "TTSConfig",
    "TaskProfile",
    "AECConfig",
    "VADConfig",
    "WakeWordConfig",
    "load_config",
    "load_dotenv",
]
